### ISSUE TITLE
Backend timeout

### ISSUE THREAD

**Issue by exp111** [popsUlfr/SDH-Notebook#2]
So after updating to 0.1.4 the plugin doesn't work anymore as it can't communicate with the backend. 
You can initially write into notes, but they aren't saved and then it will throw a lot of errors that the backend can't be reached. 

Downgrading to 0.1.3 fixes the problem

**Comment by popsUlfr** [comment]
What Steam Client channel are you on ? I can neither reproduce this on stable or beta.

Maybe the output of `sudo journalctl -u plugin_loader -a` can help.

**Comment by exp111** [comment]
SteamOS stable channel
Decky version 2.6.2 (the newest one currently)

I can try to debug it later. Maybe it'll fix itself after a reboot

**Comment by exp111** [comment]
I noticed that if i leave it open it, it works after like 30 seconds. Still annoying with the popup scan. Not sure if this is the right error, cause it happened a few times afterwards, but no new errors
```
Mar 09 17:09:32 steamdeck PluginLoader[1175]: [browser][INFO]: Installed Notebook (Version: 0.1.4)
Mar 09 17:09:32 steamdeck PluginLoader[1175]: ======== Running on http://127.0.0.1:1337 ========
Mar 09 17:09:32 steamdeck PluginLoader[1175]: (Press CTRL+C to quit)
Mar 09 17:09:32 steamdeck PluginLoader[1175]: [loader][INFO]: Loaded Notebook
Mar 09 17:09:32 steamdeck PluginLoader[1175]: [loader][INFO]: Plugin Notebook is already loaded and has requested to not be re-loaded
Mar 09 17:09:32 steamdeck PluginLoader[1175]: [loader][INFO]: Plugin Notebook is already loaded and has requested to not be re-loaded
Mar 09 17:09:32 steamdeck PluginLoader[1175]: [loader][INFO]: Plugin Notebook is already loaded and has requested to not be re-loaded
Mar 09 17:09:32 steamdeck PluginLoader[1175]: [loader][INFO]: Plugin Notebook is already loaded and has requested to not be re-loaded
Mar 09 17:09:32 steamdeck PluginLoader[1175]: [loader][INFO]: Plugin Notebook is already loaded and has requested to not be re-loaded
Mar 09 17:09:32 steamdeck PluginLoader[1187]: [plugin][INFO]: Calling Loader unload function.
Mar 09 17:09:32 steamdeck PluginLoader[1187]: [plugin][INFO]: Attempting to unload with plugin Notebook's "_unload" function.
Mar 09 17:09:32 steamdeck PluginLoader[1187]: [plugin][INFO]: Unloaded Notebook
Mar 09 17:09:33 steamdeck PluginLoader[1175]: [loader][INFO]: Loaded Notebook
Mar 09 17:09:33 steamdeck PluginLoader[2563]: Failed to start Notebook!
Mar 09 17:09:33 steamdeck PluginLoader[2563]: Traceback (most recent call last):
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "plugin.py", line 89, in _init
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "/home/deck/homebrew/plugins/SDH-Notebook/main.py", line 4, in <module>
Mar 09 17:09:33 steamdeck PluginLoader[2563]:     import decky_plugin
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "/tmp/_MEIBV044q/plugin/decky_plugin.py", line 195, in <module>
Mar 09 17:09:33 steamdeck PluginLoader[2563]:     logging.basicConfig(filename=DECKY_PLUGIN_LOG,
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "logging/__init__.py", line 2040, in basicConfig
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "logging/__init__.py", line 1169, in __init__
Mar 09 17:09:33 steamdeck PluginLoader[2563]:   File "logging/__init__.py", line 1201, in _open
Mar 09 17:09:33 steamdeck PluginLoader[2563]: PermissionError: [Errno 13] Permission denied: '/home/deck/homebrew/plugins/SDH-Notebook/plugin.log'
```

**Comment by popsUlfr** [comment]
This should be fixed in the latest pre-release version of decky: https://github.com/SteamDeckHomebrew/decky-loader/issues/390

**Comment by exp111** [comment]
Works fine now
